name: LDML Keyboard

on:
  push:
    paths:
      - 'source/*.xml'
      - '.github/workflows/kmc.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p build/
      - run: npx --package=@keymanapp/kmc -c 'kmc --error-reporting build file ldml_test.kpj'
      - uses: actions/upload-artifact@v4
        with:
          name: ldml_test
          path: build/ldml_test.kmp
